#ifndef CONTROL_MESSAGE_H
#define CONTROL_MESSAGE_H

// Control Types
#define CREATE_ROOM "CREATE_ROOM"
#define GET_ROOM_LIST "GET_ROOM_LIST"
#define LOGIN "LOGIN"
#define SIGN_UP "SIGN_UP"
#define USER_ENTER_ROOM "USER_ENTER_ROOM"
#define GET_USER_EXAM_RESULT "GET_USER_EXAM_RESULT"
#define GET_EXAM_RESULT_OF_ROOM "GET_EXAM_RESULT_OF_ROOM"
#define GET_USER_PRACTICE_RESULT "GET_USER_PRACTICE_RESULT"
#define GET_ROOM_BY_ID "GET_ROOM_BY_ID"
#define START_EXAM "START_EXAM"
#define CREATE_ROOM "CREATE_ROOM"
#define DELETE_ROOM "DELETE_ROOM" // not yet implement
#define ADD_QUESTION "ADD_QUESTION"
#define GET_ROOM_QUESTION "GET_ROOM_QUESTION"
#define GET_USER_IN_ROOM "GET_USER_IN_ROOM"
#define GET_USER_NOT_IN_ROOM "GET_USER_NOT_IN_ROOM"
#define SUBMIT_EXAM_QUESTION "SUBMIT_EXAM_QUESTION"
#define SUBMIT_EXAM "SUBMIT_EXAM"
#define USER_START_EXAM "USER_START_EXAM"
#define USER_START_PRACTICE "USER_START_PRACTICE"
#define SUBMIT_PRATICE_QUESTION "SUBMIT_PRATICE_QUESTION"
#define SUBMIT_PRACTICE "SUBMIT_PRACTICE"
#define GET_PROFILE_BY_ID "GET_PROFILE_BY_ID"
#define UPDATE_USER_BY_ID "UPDATE_USER_BY_ID"
#define GET_STATISTIC_BY_ROOM_ID "GET_STATISTIC_BY_ROOM_ID"
#define END_EXAM "END_EXAM"
// Struct Definition
typedef struct
{
    char type[50];
    char body[1024];
} ControlMessage;

#endif // CONTROL_MESSAGE_H